volumes:
  pg_data:

services:

  db:
    image: postgres:13-alpine
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  converter:
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs


