"""Add user_id foreign key to convertings

Revision ID: 8b87f7086b13
Revises: 
Create Date: 2026-08-26 13:47:04.310221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b87f7086b13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # 1. Заполняем существующие NULL значения в is_premium фолсом
    op.execute("UPDATE convertings SET is_premium = False WHERE is_premium IS NULL")
    op.execute("UPDATE users SET is_premium = False WHERE is_premium IS NULL")

    # 3. Дальше идут автосгенерированные команды Alembic (не трогаем их):
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convertings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('convertings', 'converted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('convertings', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'convertings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###

    # 2. Выполняем миграцию существующих данных: заполняем user_id на основе telegram_id!
    op.execute("""
        UPDATE convertings 
        SET user_id = users.id 
        FROM users 
        WHERE convertings.telegram_id = users.telegram_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'registration_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'convertings', type_='foreignkey')
    op.alter_column('convertings', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('convertings', 'converted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('convertings', 'user_id')
    # ### end Alembic commands ###
